<a href="https://colab.research.google.com/github/Nehanegi16/Pandas_file/blob/master/panda_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.
p1=pd.Series([1,2,4,5,6,78])
p1

0     1
1     2
2     4
3     5
4     6
5    78
dtype: int64

In [ ]:
#2. Write a Pandas program to convert a Panda module Series to Python list and it's type.
p1.tolist()

[1, 2, 4, 5, 6, 78]

In [ ]:
#3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
a=pd.Series([2, 4, 6, 8, 10])
b=pd.Series([1, 3, 5, 7, 9])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [ ]:
#4.Write a Pandas program to compare the elements of the two Pandas Series.
# Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]
a=pd.Series([2, 4, 6, 8, 10])
b=pd.Series([1, 3, 5, 7, 9])

print(a>b)
print(a==b)
print(a<b)


0    True
1    True
2    True
3    True
4    True
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [ ]:
#5.Write a Pandas program to convert a dictionary to a Pandas series.
data={'a':100,'b':200,'c':450,'d':600}
convert=pd.Series(data)
convert

a    100
b    200
c    450
d    600
dtype: int64

In [ ]:
#6. Write a Pandas program to convert a NumPy array to a Pandas series.
num_array=np.array([1,2,3,4,6,7,90])
to_pd_series=pd.Series(num_array)
to_pd_series

0     1
1     2
2     3
3     4
4     6
5     7
6    90
dtype: int64

In [ ]:
#7. Write a Pandas program to change the data type of given a column or a Series.
dtseries=pd.Series([100,300,400,'python',900,500])
dtseries
change_datatype=pd.to_numeric(dtseries, errors='coerce')
change_datatype


0    100.0
1    300.0
2    400.0
3      NaN
4    900.0
5    500.0
dtype: float64

In [ ]:
#8. Write a Pandas program to convert the first column of a DataFrame as a Series.
data={
    "col1":[1,2,3,4,5,6,7,8,9],
    "col2":[10,20,30,40,50,60,70,80,90],
    "col3":[34,59,69,60,66,70,55,67,40]
}
con=pd.DataFrame(data)
con.iloc[::,0]

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
Name: col2, dtype: int64

In [ ]:
# 9. Write a Pandas program to convert a given Series to an array.
data=pd.Series([1,3,5,8,9,23])
covert=data.values
covert


array([ 1,  3,  5,  8,  9, 23])

In [ ]:
# 10. Write a Pandas program to convert Series of lists to one Series.
# Sample Output:
# Original Series of list
# 0    [Red, Green, White]
# 1           [Red, Black]
# 2               [Yellow]
# dtype: object
# One Series
# 0       Red
# 1     Green
# 2     White
# 3       Red
# 4     Black
# 5    Yellow
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])

s = s.apply(pd.Series).stack().reset_index(drop=True)
print("One Series")
print(s)

One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [ ]:
# 11. Write a Pandas program to sort a given Series.
# Sample Output:
# Original Data Series:
# 0       100
# 1       200
# 2    python
# 3    300.12
# 4       400
# dtype: object
# 0       100
# 1       200
# 3    300.12
# 4       400
# 2    python
# dtype: object

import pandas as pd


s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object


In [ ]:
# 14. Write a Pandas program to change the order of index of a given series.
# Sample Output:
# Original Data Series:
# A    1
# B    2
# C    3
# D    4
# E    5
# dtype: int64
# Data Series after changing the order of index:
# B    2
# A    1
# C    3
# D    4
# E    5
# dtype: int64
data={'A':1,'B':2,'C':3,'D':4,'E':5}
ds=pd.Series(data)
print(ds)
print(ds.reindex(index=['B','A','C','D','E']))


A    1
B    2
C    3
D    4
E    5
dtype: int64
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [ ]:
# 16. Write a Pandas program to get the items of a given series not present in another given series.
# Sample Output:
# Original Series:
# sr1:
# 0    1
# 1    2
# 2    3
# 3    4
# 4    5
# dtype: int64
# sr2:
# 0     2
# 1     4
# 2     6
# 3     8
# 4    10
# dtype: int64

# Items of sr1 not present in sr2:
# 0    1
# 2    3
# 4    5
# dtype: int64

sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])

result=sr1[~sr1.isin(sr2)]
result

0    1
2    3
4    5
dtype: int64

In [ ]:
# 17. Write a Pandas program to get the items which are not common of two given series.
# Sample Output:
# Original Series:
# sr1:
# 0    1
# 1    2
# 2    3
# 3    4
# 4    5
# dtype: int64
# sr2:
# 0     2
# 1     4
# 2     6
# 3     8
# 4    10
# dtype: int64

# Items of a given series not present in another given series:
# 0     1
# 2     3
# 4     5
# 5     6
# 6     8
# 7    10

sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])

s11=pd.Series(np.intersect1d(sr1,sr2))
print(s11)
s22=pd.Series(np.union1d(sr1,sr2))
print(s22)
result = s11[~s11.isin(s22)]
print(result)

0    2
1    4
dtype: int64
0     1
1     2
2     3
3     4
4     5
5     6
6     8
7    10
dtype: int64
Series([], dtype: int64)


In [ ]:
# 18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.
# Sample Output:
# Original Series:
# 0      3.000938
# 1     11.370722
# 2     14.612143

# ....

# 17    14.118931
# 18     8.247458
# 19     5.526727
# dtype: float64

# Minimum, 25th percentile, median, 75th, and maximum of a given series:
# [ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]

import pandas as pd
import numpy as np
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print("Original Series:")
print(num_series)
result = np.percentile(num_series, q=[0, 25, 50, 75, 100])
print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
print(result)

Original Series:
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


In [ ]:
# 19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.
# Sample Output:
# Original Series:
# 0     1
# 1     7
# 2     1
# 3     6

# ...


# 37    0
# 38    4
# 39    8
# dtype: object
# Frequency of each unique value of the said series.
# 0    9
# 2    7
# 9    6
# ....
# 3    2
# 4    1
# 5    1
# dtype: int64

num1=pd.Series(np.random.RandomState((10)))
re=num1.normal(10,4,20)

AttributeError: 'Series' object has no attribute 'normal'